//
//  MenuScene.swift
//  Loot Wars
//
//  The door into the game: a living map drifting behind a veil, the name, and three
//  buttons.
//
//  FOUR VERSIONS CAME BEFORE THIS AND EACH FAILED IN ITS OWN DIRECTION, which is
//  worth keeping because the failures are the argument for what is here now. The
//  first put the game's furniture on the screen - giant grass checks, a token, a
//  crate and a bomb bobbing about - and looked like the game with the level
//  missing. The second went dark and typographic: clean, and it had nothing to do
//  with this game. The third was a flat field of the map's green with a drawn logo
//  and one button on it, which was honest and read as a placeholder, because a flat
//  colour is what a screen looks like before anybody has designed it.
//
//  This one takes the thing all three were reaching for and simply uses it: THE
//  MAP. Not a picture of the map, and not the game's furniture arranged
//  decoratively - a real one, generated by the real generator, drifting slowly
//  behind a light veil. It belongs to Loot Wars because it IS Loot Wars, and it
//  needs no art, because the map has always drawn itself.
//
//  Now with its bases built and their people in them - see MenuBackdrop. A World
//  is made for that, but nothing simulates it: nothing is stepped and nothing
//  thinks. The people are puppets walked about inside their own walls.
//
//  The drift is two sine waves on periods that do not divide into each other, which
//  is the same trick the old logo used for its float and sway and the crates use on
//  the map. A single direction reads as a pan; a loop reads as a loop; two clocks
//  that never come back into phase read as a place that is simply there.
//
//  HIERARCHY IS THE WHOLE LAYOUT. One solid white pill you came here to press, two
//  outlined circles that say there is more, and a wordmark that is type rather than
//  a picture. Nothing else. On a screen where the background is moving, anything
//  decorative in the foreground is noise competing with the one thing that matters.
//

import CoreImage
import SpriteKit
import UIKit

final class MenuScene: SKScene {

    // MARK: - The drifting map

    /// The map behind the buttons, with its bases built and their people in them
    /// - see MenuBackdrop. Moved as one by the drift.
    private let backdrop = MenuBackdrop()

    /// The blur over it, and the thing that moves.
    ///
    /// NOT rasterised any more. It was, back when the map behind it stood still:
    /// a rasterised effect node keeps its blurred bitmap until its contents
    /// change, so a still map was blurred once and never again. The people move,
    /// so the blur is redone every frame - and kept cheap the standard way: the
    /// map is drawn small (sceneryScale), blurred there, and scaled back up. The
    /// upscale only adds softness, which is the effect being paid for anyway.
    private let blur = SKEffectNode()

    /// How small the map is drawn before it is blurred and scaled back up. Small
    /// is what keeps a per-frame blur cheap: about a fifth of the pixels of a
    /// full-size map.
    private static let sceneryScale: CGFloat = 0.3

    /// In points of the downscaled map; the blur you see is about three times
    /// this - the same softness as the old still backdrop.
    private static let blurRadius: Double = 3.6

    /// How far the view wanders from the middle of the map, as a share of the
    /// slack between the map and the screen.
    ///
    /// Not all of it: the map's outermost ring is sealed edge, and drifting into
    /// the corner would put the wall of the world on screen - which is the one part
    /// of the map that looks like the edge of a level rather than like a place.
    private static let driftShare: CGFloat = 0.62

    /// Seconds for a full cycle of each axis. Deliberately not multiples of each
    /// other and deliberately long: the horizontal takes nearly a minute and a half
    /// and the vertical over two, so the pair does not return to where it started
    /// for the better part of an hour. Nobody sits on a menu that long, which is
    /// the point - within any real visit there is no repeat to notice.
    private static let driftPeriodX: Double = 87
    private static let driftPeriodY: Double = 134

    /// How far in the map is drawn.
    ///
    /// 0.9, which is very nearly the scale the game itself plays at - about
    /// twenty-one tiles across a phone against the game's twenty-two. Pulling back
    /// further was the first instinct and it is wrong twice over.
    ///
    /// It looks wrong: at 0.6 you see thirty tiles at once and the screen reads as
    /// a MINIMAP rather than as a place - trees become dots, a base becomes a
    /// coloured square. The map is attractive at the size it was drawn to be seen
    /// at and not at half of it.
    ///
    /// And it kills the drift, which is the part worth writing down because it is
    /// the opposite of what you would guess. The view can only wander across
    /// whatever the map has SPARE over the screen, so zooming out shrinks the
    /// drawn map towards the size of the glass and the slack goes with it. At 0.62
    /// an iPad had 17 points of horizontal travel - which is to say none, a still
    /// image. At 0.9 it has 192, and a phone has 356.
    private static let backdropZoom: CGFloat = 0.9

    private var driftClock: TimeInterval = 0
    private var lastFrame: TimeInterval = 0

    // MARK: - The front

    private let wordmark = SKNode()
    private var playButton: MenuButtonNode?
    private var infoButton: MenuButtonNode?
    private var settingsButton: MenuButtonNode?
    private let sheet = MenuSheetNode()

    /// The settings page and the About page behind it - see SettingsSheetContent.
    private let settingsContent = SettingsSheetContent()
    private let aboutContent = AboutSheetContent()
    private let legalContent = LegalSheetContent()

    /// How to Play, behind the Info button - see HowToPlayContent.
    private let howToPlay = HowToPlayContent()

    /// Your level, top left, and the roadmap behind it.
    private var levelBadge: LevelBadgeNode?
    /// Whether the badge was drawn in dev mode, so turning it on or off in
    /// Settings redraws it.
    private var badgeDevMode = false
    private let roadmap = RoadmapSheetContent()
    private let featureDetail = FeatureDetailContent()

    /// Set once the scene has handed the game over, so a second tap on a button
    /// that is still animating cannot present a second match.
    private var starting = false

    class func newMenuScene() -> MenuScene {
        let scene = MenuScene(size: CGSize(width: 1024, height: 768))
        scene.scaleMode = .resizeFill
        return scene
    }

    override func didMove(to view: SKView) {
        // Settings to About and back, inside the one sheet.
        settingsContent.onAbout = { [weak self] in
            guard let self else { return }
            self.sheet.show(title: "ABOUT", content: self.aboutContent)
        }
        aboutContent.onBack = { [weak self] in
            guard let self else { return }
            self.sheet.show(title: "SETTINGS", content: self.settingsContent)
        }

        // About to the Privacy Policy or the Terms, and back.
        aboutContent.onOpen = { [weak self] document in
            guard let self else { return }
            self.legalContent.document = document
            self.sheet.show(title: document.title.uppercased(), content: self.legalContent)
        }
        legalContent.onBack = { [weak self] in
            guard let self else { return }
            self.sheet.show(title: "ABOUT", content: self.aboutContent)
        }

        // A roadmap card to its own page, and back.
        roadmap.onSelect = { [weak self] feature, level in
            guard let self else { return }
            self.featureDetail.feature = feature
            self.featureDetail.level = level
            self.sheet.show(title: feature.title.uppercased(), content: self.featureDetail)
        }
        featureDetail.onBack = { [weak self] in
            guard let self else { return }
            self.sheet.show(title: "ROADMAP", content: self.roadmap)
        }

        // Before anything asks for a sound. See SoundPlayer.warm.
        SoundPlayer.shared.warm()

        backgroundColor = RenderPalette.floorLight
        removeAllChildren()
        buildScenery()
        build()
    }

    override func didChangeSize(_ oldSize: CGSize) {
        // The scenery survives a resize: it is a map, its contents do not depend on
        // the screen, and rebuilding it would re-bake the terrain image and restart
        // the drift from the middle every time the device turned.
        guard scene != nil, !children.isEmpty else { return }
        build()
    }

    // MARK: - Behind the glass

    /// The map, its bases and their people, built once per visit.
    ///
    /// A fresh seed each time the menu is opened, so the screen behind the buttons
    /// is a different place every time you come back to it.
    ///
    /// Behind frosted glass, as before - the bases and people come through it as
    /// shapes and colour, which is enough to say what the game is.
    private func buildScenery() {
        backdrop.build()
        backdrop.node.removeFromParent()
        backdrop.node.setScale(MenuScene.sceneryScale)

        // shouldEnableEffects is set from whether the filter actually came back:
        // CIFilter is looked up by name, and an effect node with effects on and no
        // filter draws nothing - so the worst case is a sharp map, not a blank one.
        let gaussian = CIFilter(name: "CIGaussianBlur",
                                parameters: ["inputRadius": MenuScene.blurRadius])

        blur.removeAllChildren()
        blur.removeFromParent()
        blur.filter = gaussian
        blur.shouldEnableEffects = gaussian != nil
        blur.shouldRasterize = false
        blur.setScale(MenuScene.backdropZoom / MenuScene.sceneryScale)
        blur.zPosition = -10
        blur.addChild(backdrop.node)
        addChild(blur)

        let glass = SKSpriteNode(color: RenderPalette.menuVeil, size: .zero)
        glass.name = "glass"
        glass.zPosition = -9
        addChild(glass)
    }

    /// Where the view sits this instant.
    ///
    /// Read off a clock rather than animated, and that is not a style choice: the
    /// position is rewritten every frame, and a value rewritten every frame cannot
    /// also be driven by an SKAction - the action loses. The whole renderer folder
    /// has this note on it.
    override func update(_ currentTime: TimeInterval) {
        if lastFrame == 0 { lastFrame = currentTime }
        // Clamped, so coming back from the app switcher does not teleport the view
        // across the map in one frame.
        let dt = min(0.25, currentTime - lastFrame)
        lastFrame = currentTime

        // The map behind the glass holds still while a sheet is up, and its blur
        // is cached rather than redrawn: a full-screen blur every frame was
        // costing the frames a scrolling sheet needs. It picks up where it left
        // off when the sheet closes.
        let frozen = sheet.isOpen
        if blur.shouldRasterize != frozen { blur.shouldRasterize = frozen }
        if !frozen {
            driftClock += dt
            backdrop.update(dt: dt)
        }

        if let insets = view?.safeAreaInsets, insets != laidOutInsets {
            buildRecord()
        } else if Prefs.devMode != badgeDevMode {
            buildLevelBadge()
        }

        let mapWide = GridGeometry.length(ofTiles: Double(GameConfig.Map.width))
            * MenuScene.backdropZoom
        let mapTall = GridGeometry.length(ofTiles: Double(GameConfig.Map.height))
            * MenuScene.backdropZoom

        // The slack is whatever the map has over the screen. On a very wide screen
        // against a narrow map this can go negative, and max pins it at zero rather
        // than drifting the wrong way and showing the void beside the world.
        let slackX = max(0, (mapWide - size.width) / 2) * MenuScene.driftShare
        let slackY = max(0, (mapTall - size.height) / 2) * MenuScene.driftShare

        let phaseX = driftClock * 2 * .pi / MenuScene.driftPeriodX
        let phaseY = driftClock * 2 * .pi / MenuScene.driftPeriodY

        blur.position = CGPoint(
            x: size.width / 2 - mapWide / 2 + slackX * CGFloat(sin(phaseX)),
            y: size.height / 2 - mapTall / 2 + slackY * CGFloat(sin(phaseY)))
    }

    // MARK: - The front

    private func build() {
        starting = false

        if let glass = childNode(withName: "glass") as? SKSpriteNode {
            glass.size = CGSize(width: size.width * 1.4, height: size.height * 1.4)
            glass.position = CGPoint(x: size.width / 2, y: size.height / 2)
        }

        let middle = CGPoint(x: size.width / 2, y: size.height / 2)

        // Laid out straight off Heath's mock-up, as shares of one unit: the
        // screen's height, or its width over 1.9 on anything squarer than the
        // mock-up was drawn at (an iPad), so the whole arrangement shrinks as one
        // rather than the buttons running off the sides.
        let unit = min(size.height, size.width / 1.9)

        // The name near the top, the wide play button dead centre, the two
        // squares under it either side of the middle.
        buildWordmark(centredOn: CGPoint(x: middle.x, y: middle.y + unit * 0.346),
                      fontSize: unit * 0.2)

        let squareSide = unit * 0.184
        buildButtons(centredOn: middle,
                     playSize: CGSize(width: unit * 0.645, height: unit * 0.301),
                     squareSide: squareSide,
                     squareOffset: unit * 0.144,
                     squareRowY: middle.y - unit * 0.316)

        buildRecord()

        if sheet.parent == nil { addChild(sheet) }
        sheet.position = middle
        sheet.layOut(for: size)
    }

    /// The name, as a logo: rounded heavy letters, white with a thick black
    /// outline - see LogoArt. One line, lower case, as Heath drew it.
    ///
    /// It floats, and that is all it does - there is a map moving behind it.
    private func buildWordmark(centredOn centre: CGPoint, fontSize: CGFloat) {
        wordmark.removeAllActions()
        wordmark.removeAllChildren()
        wordmark.removeFromParent()
        wordmark.position = centre
        wordmark.alpha = 1
        wordmark.setScale(1)
        addChild(wordmark)

        let logo = LogoArt.make("loot wars", size: fontSize)

        // Everything that makes it a logo rather than a title rides on `badge`,
        // so the float below can keep moving the wordmark itself.
        let badge = SKNode()
        badge.zRotation = 0
        wordmark.addChild(badge)

        // A soft shadow under it, so it sits ABOVE the map rather than on it.
        // The logo's own shape, in black, blurred and dropped a little - blurred
        // once and kept, since it never changes.
        let shadow = SKEffectNode()
        if let soft = CIFilter(name: "CIGaussianBlur",
                               parameters: ["inputRadius": Double(fontSize) * 0.09]) {
            shadow.filter = soft
            shadow.shouldEnableEffects = true
        }
        shadow.shouldRasterize = true
        shadow.alpha = 0.32
        shadow.position = CGPoint(x: 0, y: -fontSize * 0.09)
        let shape = SKSpriteNode(texture: logo.texture, size: logo.size)
        shape.color = .black
        shape.colorBlendFactor = 1
        shadow.addChild(shape)
        badge.addChild(shadow)

        let sprite = SKSpriteNode(texture: logo.texture, size: logo.size)
        badge.addChild(sprite)

        // In with a pop, the way the buttons press: up past full size and
        // settling, rather than a fade.
        wordmark.alpha = 0
        badge.setScale(0.6)
        wordmark.run(.fadeIn(withDuration: 0.15))
        badge.run(.sequence([
            .scale(to: 1.08, duration: 0.18),
            .scale(to: 0.97, duration: 0.1),
            .scale(to: 1, duration: 0.08)
        ]))

        // And a slow sway on top of the float - a degree either way, on its own
        // clock, so the logo is alive without ever moving much.
        // Centred on level, so it never looks like it is leaning.
        let sway = SKAction.sequence([.rotate(toAngle: -0.018, duration: 3.1),
                                      .rotate(toAngle: 0.018, duration: 3.1)])
        sway.timingMode = .easeInEaseOut
        badge.run(.repeatForever(sway))

        let float = SKAction.sequence([.moveBy(x: 0, y: 5, duration: 2.3),
                                       .moveBy(x: 0, y: -5, duration: 2.3)])
        float.timingMode = .easeInEaseOut
        wordmark.run(.repeatForever(float), withKey: "float")
    }

    private func buildButtons(centredOn playCentre: CGPoint,
                              playSize: CGSize,
                              squareSide: CGFloat,
                              squareOffset: CGFloat,
                              squareRowY: CGFloat) {
        for old in [playButton, infoButton, settingsButton] { old?.removeFromParent() }

        let play = MenuButtonNode(play: playSize.width, height: playSize.height,
                                  tone: RenderPalette.menuPlay)
        play.position = playCentre
        play.zPosition = 10
        addChild(play)
        playButton = play

        let info = MenuButtonNode(glyph: Glyphs.info, side: squareSide,
                                  tone: RenderPalette.menuInfo)
        let settings = MenuButtonNode(glyph: Glyphs.gear, side: squareSide,
                                      tone: RenderPalette.menuSettings)

        // Either side of the middle, on one line: the same kind of thing, so the
        // same size - ranking them against each other would be a third level of
        // hierarchy on a screen that needs two.
        info.position = CGPoint(x: playCentre.x - squareOffset, y: squareRowY)
        settings.position = CGPoint(x: playCentre.x + squareOffset, y: squareRowY)

        for button in [info, settings] {
            button.zPosition = 10
            button.alpha = 0
            button.run(.sequence([.wait(forDuration: 0.12),
                                  .fadeAlpha(to: 1, duration: 0.3)]))
            addChild(button)
        }

        infoButton = info
        settingsButton = settings

        // Offset from the wordmark's float, so the two never nod together. Two
        // things pulsing in step read as one mechanism, which is the note this
        // screen must not hit: the button would look like part of the title.
        play.breathe(after: 0.5)
    }

    /// What the game remembers about you, tucked into the top-right corner.
    /// Nothing at all the first time.
    ///
    /// Two right-aligned lines - best score over matches played - so it reads as
    /// a small stat block rather than a sentence, and stays out of the way of the
    /// title and the buttons. Inset from the safe area, so it never sits under
    /// the notch or the rounded corner.
    /// The safe area the record was last placed against. It is often still zero
    /// on the frame the scene first appears and only filled in a moment later,
    /// which is how the record ended up under the notch - so update() watches for
    /// it changing and places the record again.
    private var laidOutInsets: UIEdgeInsets = .zero

    /// Bottom left - the top of the screen belongs to the logo - and clear of the
    /// notch the same way the record is.
    private func buildLevelBadge() {
        levelBadge?.removeFromParent()
        badgeDevMode = Prefs.devMode

        let margin: CGFloat = 18
        let insets = view?.safeAreaInsets ?? .zero
        let side = max(insets.left, insets.right)

        let badge = LevelBadgeNode()
        badge.position = CGPoint(x: side + margin,
                                 y: insets.bottom + margin + LevelBadgeNode.size.height)
        badge.zPosition = 10
        addChild(badge)
        levelBadge = badge
    }

    private func buildRecord() {
        childNode(withName: "record")?.removeFromParent()
        laidOutInsets = view?.safeAreaInsets ?? .zero
        buildLevelBadge()
        guard Prefs.matchesFinished > 0 else { return }

        let matches = Prefs.matchesFinished
        let played = "\(matches) MATCH\(matches == 1 ? "" : "ES")"

        // Clear of the notch whichever way the phone is turned: the larger of
        // the two side insets, since the notch can be on either side in
        // landscape and the record should not jump across when it flips.
        let margin: CGFloat = 18
        let insets = view?.safeAreaInsets ?? .zero
        let side = max(insets.left, insets.right)
        let right = size.width - side - margin
        let top = size.height - insets.top - margin

        let record = SKNode()
        record.name = "record"
        record.position = CGPoint(x: right, y: top)
        record.zPosition = 10

        let best = SKLabelNode()
        best.attributedText = MenuButtonNode.text("BEST \(Prefs.bestScore)",
                                                  size: 15, weight: .bold,
                                                  colour: SKColor(white: 0, alpha: 0.62))
        best.horizontalAlignmentMode = .right
        best.verticalAlignmentMode = .top
        record.addChild(best)

        let count = SKLabelNode()
        count.attributedText = MenuButtonNode.text(played,
                                                   size: 12, weight: .semibold,
                                                   colour: SKColor(white: 0, alpha: 0.45))
        count.horizontalAlignmentMode = .right
        count.verticalAlignmentMode = .top
        count.position = CGPoint(x: 0, y: -20)
        record.addChild(count)

        addChild(record)
    }

    // Type for this whole screen lives in MenuButtonNode.text - one helper, one
    // typeface, one place. It was duplicated here and in the sheet, which is how
    // three files end up set in two and a half different fonts.

    // MARK: - Pressing it

    #if os(iOS) || os(tvOS)
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard let touch = touches.first, let view else { return }
        let point = touch.location(in: self)

        // The sheet gets first refusal on everything while it is up, which is what
        // makes it a sheet rather than a picture of one: nothing behind it can be
        // pressed through it.
        if sheet.isOpen {
            let local = touch.location(in: sheet)
            if sheet.closes(localPoint: local) {
                SoundPlayer.shared.play(.exit)
                sheet.dismiss()
            } else {
                // On the card: the settings rows take their own taps, and the
                // How to Play pages start a swipe.
                sheet.tap(localPoint: local)
                sheet.dragBegan(localPoint: local)
            }
            return
        }

        guard !starting else { return }

        if let play = playButton,
           play.contains(localPoint: CGPoint(x: point.x - play.position.x,
                                             y: point.y - play.position.y)) {
            starting = true

            // On the press rather than when the match appears. The button's
            // animation and the fade to the map take the better part of half a
            // second between them, and a sound that arrives at the end of that
            // belongs to the scene change; one that arrives on the press belongs
            // to the finger.
            SoundPlayer.shared.play(.play)

            // And the rest of the screen stands down, so the button is the only
            // thing moving at the moment it is pressed.
            wordmark.removeAction(forKey: "float")

            play.press { [weak view] in
                view?.presentScene(GameScene.newGameScene(),
                                   transition: .fade(withDuration: 0.35))
            }
            return
        }

        if let badge = levelBadge,
           badge.contains(localPoint: CGPoint(x: point.x - badge.position.x,
                                              y: point.y - badge.position.y)) {
            SoundPlayer.shared.play(.select)
            badge.press { [weak self] in
                guard let self else { return }
                self.sheet.open(title: "ROADMAP", content: self.roadmap, on: self.size)
            }
            return
        }

        if let info = infoButton,
           info.contains(localPoint: CGPoint(x: point.x - info.position.x,
                                             y: point.y - info.position.y)) {
            SoundPlayer.shared.play(.select)
            info.press { [weak self] in
                guard let self else { return }
                self.sheet.open(title: "HOW TO PLAY",
                                content: self.howToPlay,
                                on: self.size)
            }
            return
        }

        if let settings = settingsButton,
           settings.contains(localPoint: CGPoint(x: point.x - settings.position.x,
                                                 y: point.y - settings.position.y)) {
            SoundPlayer.shared.play(.select)
            settings.press { [weak self] in
                guard let self else { return }
                self.sheet.open(title: "SETTINGS",
                                content: self.settingsContent,
                                on: self.size)
            }
        }
    }

    // Swipes on the sheet - the How to Play pages. Nothing else on this screen
    // follows a finger.
    override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard sheet.isOpen, let touch = touches.first else { return }
        sheet.dragMoved(localPoint: touch.location(in: sheet))
    }

    override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard sheet.isOpen, let touch = touches.first else { return }
        sheet.dragEnded(localPoint: touch.location(in: sheet))
    }

    override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard sheet.isOpen, let touch = touches.first else { return }
        sheet.dragEnded(localPoint: touch.location(in: sheet))
    }
    #endif
}
