//
//  MenuScene.swift
//  Loot Wars
//
//  The door into the game: a map drifting behind glass, the name, and three
//  buttons.
//
//  FOUR VERSIONS CAME BEFORE THIS AND EACH FAILED IN ITS OWN DIRECTION, which is
//  worth keeping because the failures are the argument for what is here now. The
//  first put the game's furniture on the screen - giant grass checks, a token, a
//  crate and a bomb bobbing about - and looked like the game with the level
//  missing. The second went dark and typographic: clean, and it had nothing to do
//  with this game. The third was a flat field of the map's green with a drawn logo
//  and one button on it, which was honest and read as a placeholder, because a flat
//  colour is what a screen looks like before anybody has designed it.
//
//  This one takes the thing all three were reaching for and simply uses it: THE
//  MAP. Not a picture of the map, and not the game's furniture arranged
//  decoratively - a real one, generated by the real generator, drifting slowly
//  behind a dark scrim. It belongs to Loot Wars because it IS Loot Wars, and it
//  needs no art, because the map has always drawn itself.
//
//  It costs almost nothing, and the objection the old file raised against a menu
//  over the game does not apply. That objection was about building a WORLD - eight
//  actors, eight brains, forty crates and a simulation - before anybody had pressed
//  anything, and then tearing it down. There is no world here. MapFactory hands
//  back terrain, claims and trees as plain data; three renderers that take that
//  data directly draw it once into a node that is then never touched again. Nothing
//  is stepped, nothing is synced, nothing thinks.
//
//  The drift is two sine waves on periods that do not divide into each other, which
//  is the same trick the old logo used for its float and sway and the crates use on
//  the map. A single direction reads as a pan; a loop reads as a loop; two clocks
//  that never come back into phase read as a place that is simply there.
//
//  HIERARCHY IS THE WHOLE LAYOUT. One solid white pill you came here to press, two
//  outlined circles that say there is more, and a wordmark that is type rather than
//  a picture. Nothing else. On a screen where the background is moving, anything
//  decorative in the foreground is noise competing with the one thing that matters.
//

import CoreImage
import SpriteKit
import UIKit

final class MenuScene: SKScene {

    // MARK: - The drifting map

    /// The blur, and the thing that MOVES.
    ///
    /// Everything about this node is arranged around one SpriteKit fact: a
    /// rasterised effect node caches its contents as a bitmap, and that cache is
    /// thrown away the moment its CONTENTS change. So the drift moves this node,
    /// not the map inside it - moving a child would re-blur the whole map sixty
    /// times a second - and the trees' idle spin is stopped, because an SKAction
    /// running inside here would do exactly the same thing every frame forever.
    private let blur = SKEffectNode()

    /// Everything behind the glass, moved as one.
    private let scenery = SKNode()
    private let tiles = TileMapRenderer()
    private let claims = ClaimRenderer()
    private let trees = TreeRenderer()

    /// How far the view wanders from the middle of the map, as a share of the
    /// slack between the map and the screen.
    ///
    /// Not all of it: the map's outermost ring is sealed edge, and drifting into
    /// the corner would put the wall of the world on screen - which is the one part
    /// of the map that looks like the edge of a level rather than like a place.
    private static let driftShare: CGFloat = 0.62

    /// Seconds for a full cycle of each axis. Deliberately not multiples of each
    /// other and deliberately long: the horizontal takes nearly a minute and a half
    /// and the vertical over two, so the pair does not return to where it started
    /// for the better part of an hour. Nobody sits on a menu that long, which is
    /// the point - within any real visit there is no repeat to notice.
    private static let driftPeriodX: Double = 87
    private static let driftPeriodY: Double = 134

    /// How small the map is DRAWN before it is blurred and scaled back up.
    ///
    /// This is the whole cost control, and it is the standard way a cheap blur is
    /// done: downsample, blur, upsample. A gaussian is expensive in proportion to
    /// the area it covers and the radius it covers it with, and the map is 2016
    /// points square. Rasterising that at full size costs about sixty-five
    /// megabytes on a 2x screen and a hundred and forty on a 3x one, for a
    /// backdrop. Drawn at two fifths it is nine and twenty-three, and the upscale
    /// adds softness for nothing - which is the effect being paid for anyway.
    private static let sceneryScale: CGFloat = 0.4

    /// In points of the DOWNSCALED map, so the blur you see is about twice this.
    private static let blurRadius: Double = 5

    /// How far in the map is drawn.
    ///
    /// 0.9, which is very nearly the scale the game itself plays at - about
    /// twenty-one tiles across a phone against the game's twenty-two. Pulling back
    /// further was the first instinct and it is wrong twice over.
    ///
    /// It looks wrong: at 0.6 you see thirty tiles at once and the screen reads as
    /// a MINIMAP rather than as a place - trees become dots, a base becomes a
    /// coloured square. The map is attractive at the size it was drawn to be seen
    /// at and not at half of it.
    ///
    /// And it kills the drift, which is the part worth writing down because it is
    /// the opposite of what you would guess. The view can only wander across
    /// whatever the map has SPARE over the screen, so zooming out shrinks the
    /// drawn map towards the size of the glass and the slack goes with it. At 0.62
    /// an iPad had 17 points of horizontal travel - which is to say none, a still
    /// image. At 0.9 it has 192, and a phone has 356.
    private static let backdropZoom: CGFloat = 0.9

    private var driftClock: TimeInterval = 0
    private var lastFrame: TimeInterval = 0

    // MARK: - The front

    private let wordmark = SKNode()
    private var playButton: MenuButtonNode?
    private var infoButton: MenuButtonNode?
    private var settingsButton: MenuButtonNode?
    private let sheet = MenuSheetNode()

    /// Set once the scene has handed the game over, so a second tap on a button
    /// that is still animating cannot present a second match.
    private var starting = false

    class func newMenuScene() -> MenuScene {
        let scene = MenuScene(size: CGSize(width: 1024, height: 768))
        scene.scaleMode = .resizeFill
        return scene
    }

    override func didMove(to view: SKView) {
        // Before anything asks for a sound. See SoundPlayer.warm.
        SoundPlayer.shared.warm()

        backgroundColor = RenderPalette.floorLight
        removeAllChildren()
        buildScenery()
        build()
    }

    override func didChangeSize(_ oldSize: CGSize) {
        // The scenery survives a resize: it is a map, its contents do not depend on
        // the screen, and rebuilding it would re-bake the terrain image and restart
        // the drift from the middle every time the device turned.
        guard scene != nil, !children.isEmpty else { return }
        build()
    }

    // MARK: - Behind the glass

    /// The map, drawn once.
    ///
    /// A fresh seed each time the menu is opened, so the screen behind the buttons
    /// is a different place every time you come back to it - which costs one call
    /// and is most of why this reads as a game rather than as a background.
    private func buildScenery() {
        let generated = MapFactory.generate(seed: UInt64.random(in: 0..<UInt64.max))

        tiles.build(from: generated.map)
        claims.build(claims: generated.claims)
        trees.build(patches: generated.trees)

        // The trees, settled and deepened.
        //
        // TWO fixes in one pass, and they are unrelated except that this is the one
        // moment the sprites are reachable.
        //
        // Stopping the spin is the load-bearing one: these carry a repeating
        // SKAction, and a running action inside a rasterised effect node invalidates
        // its cache every frame, which would turn a blur computed once into a blur
        // computed sixty times a second. Nobody can see a tree turning through ten
        // points of blur in any case.
        //
        // The tint is the look. The art is a pale green against a pale green lawn,
        // which is right on the map - a tree is scenery and should not shout - and
        // washed out here, where the veil lifts everything and takes what little
        // separation they had. Pulled a third of the way towards the deep green
        // this game already uses for impassable scenery, they read as woods again.
        for sprite in trees.node.children.compactMap({ $0 as? SKSpriteNode }) {
            sprite.removeAllActions()
            sprite.color = RenderPalette.terrain
            sprite.colorBlendFactor = 0.34
        }

        scenery.removeAllChildren()
        scenery.setScale(MenuScene.sceneryScale)
        scenery.addChild(tiles.node)
        scenery.addChild(claims.node)
        scenery.addChild(trees.node)

        // Blurred, and cached. shouldEnableEffects is set from whether the filter
        // actually came back rather than assumed: CIFilter is looked up by NAME, so
        // it is the one thing on this screen that can fail at runtime, and an
        // effect node with effects on and no filter draws nothing at all. Off, it
        // passes its children straight through - so the worst case is a sharp map
        // rather than a blank screen.
        let gaussian = CIFilter(name: "CIGaussianBlur",
                                parameters: ["inputRadius": MenuScene.blurRadius])

        blur.removeAllChildren()
        blur.removeFromParent()
        blur.filter = gaussian
        blur.shouldEnableEffects = gaussian != nil
        blur.shouldRasterize = true
        blur.setScale(MenuScene.backdropZoom / MenuScene.sceneryScale)
        blur.zPosition = -10
        blur.addChild(scenery)
        addChild(blur)

        // The veil. White rather than black - see RenderPalette.menuVeil, which
        // carries that argument, because it is about this game's particular colours
        // rather than about menus.
        //
        // Sized well past the screen so the corners stay covered on any device, and
        // rebuilt never: it is one rectangle.
        let glass = SKSpriteNode(color: RenderPalette.menuVeil, size: .zero)
        glass.name = "glass"
        glass.zPosition = -9
        addChild(glass)
    }

    /// Where the view sits this instant.
    ///
    /// Read off a clock rather than animated, and that is not a style choice: the
    /// position is rewritten every frame, and a value rewritten every frame cannot
    /// also be driven by an SKAction - the action loses. The whole renderer folder
    /// has this note on it.
    override func update(_ currentTime: TimeInterval) {
        if lastFrame == 0 { lastFrame = currentTime }
        // Clamped, so coming back from the app switcher does not teleport the view
        // across the map in one frame.
        driftClock += min(0.25, currentTime - lastFrame)
        lastFrame = currentTime

        let mapWide = GridGeometry.length(ofTiles: Double(GameConfig.Map.width))
            * MenuScene.backdropZoom
        let mapTall = GridGeometry.length(ofTiles: Double(GameConfig.Map.height))
            * MenuScene.backdropZoom

        // The slack is whatever the map has over the screen. On a very wide screen
        // against a narrow map this can go negative, and max pins it at zero rather
        // than drifting the wrong way and showing the void beside the world.
        let slackX = max(0, (mapWide - size.width) / 2) * MenuScene.driftShare
        let slackY = max(0, (mapTall - size.height) / 2) * MenuScene.driftShare

        let phaseX = driftClock * 2 * .pi / MenuScene.driftPeriodX
        let phaseY = driftClock * 2 * .pi / MenuScene.driftPeriodY

        // The EFFECT node, not the map inside it. See the note on `blur`.
        blur.position = CGPoint(
            x: size.width / 2 - mapWide / 2 + slackX * CGFloat(sin(phaseX)),
            y: size.height / 2 - mapTall / 2 + slackY * CGFloat(sin(phaseY)))
    }

    // MARK: - The front

    private func build() {
        starting = false

        if let glass = childNode(withName: "glass") as? SKSpriteNode {
            glass.size = CGSize(width: size.width * 1.4, height: size.height * 1.4)
            glass.position = CGPoint(x: size.width / 2, y: size.height / 2)
        }

        let middle = CGPoint(x: size.width / 2, y: size.height / 2)

        // Sized off the SHORTER side, so the block keeps its proportions on a tall
        // phone and an iPad alike rather than growing only sideways.
        let unit = min(size.width, size.height)

        let playWidth = min(size.width * 0.46, 300)
        let playHeight = max(52, min(unit * 0.15, 64))
        let iconSide = max(44, min(unit * 0.125, 54))

        let gapUnderMark: CGFloat = unit * 0.09
        let gapUnderPlay: CGFloat = unit * 0.06

        // The whole stack is centred as a block, so a tall screen gets more air
        // around it rather than wider gaps inside it.
        let markHeight = unit * 0.20
        let block = markHeight + gapUnderMark + playHeight + gapUnderPlay + iconSide
        var y = middle.y + block / 2

        y -= markHeight / 2
        buildWordmark(centredOn: CGPoint(x: middle.x, y: y), height: markHeight)
        y -= markHeight / 2 + gapUnderMark

        y -= playHeight / 2
        buildButtons(centredOn: CGPoint(x: middle.x, y: y),
                     playSize: CGSize(width: playWidth, height: playHeight),
                     iconSide: iconSide,
                     iconRowY: y - playHeight / 2 - gapUnderPlay - iconSide / 2)

        buildRecord(centredOn: CGPoint(x: middle.x, y: middle.y - block / 2 - unit * 0.07))

        if sheet.parent == nil { addChild(sheet) }
        sheet.position = middle
        sheet.layOut(for: size)
    }

    /// The name, as TYPE.
    ///
    /// It was a drawn logo and before that a single line of black type, and it is
    /// two lines of tracked white type now. The picture went because a wordmark is
    /// not a thing this game needs an artist for: the name is two four-letter words
    /// of equal length, which is the one case where stacking them gives you a solid
    /// rectangle of type for free - and a solid rectangle of heavy letterforms IS
    /// the logo. Anything drawn on top of that was decoration on a shape that was
    /// already doing the job.
    ///
    /// Wide tracking and tight leading, which is the whole look: the letters are
    /// pushed apart and the lines pulled together, so the block reads as one mark
    /// rather than as a sentence. It is also the only treatment that survives being
    /// rendered at any size on any screen, which a bitmap does not.
    ///
    /// It floats, and that is all it does. The old one floated, swayed and shrugged
    /// on three clocks, which was charming when it was the only thing on the screen
    /// and is noise now that there is a map moving behind it.
    private func buildWordmark(centredOn centre: CGPoint, height: CGFloat) {
        wordmark.removeAllActions()
        wordmark.removeAllChildren()
        wordmark.removeFromParent()
        wordmark.position = centre
        wordmark.alpha = 1
        wordmark.setScale(1)
        addChild(wordmark)

        // Not named `size`: that is the scene's own, and a local shadowing it three
        // lines above a layout calculation is a trap left for whoever edits next.
        let type = height * 0.48
        let leading = type * 0.88

        for (index, word) in ["LOOT", "WARS"].enumerated() {
            let line = SKLabelNode()
            line.attributedText = MenuButtonNode.text(word, size: type,
                                                      weight: .black,
                                                      kern: type * 0.04,
                                                      colour: RenderPalette.menuInk)
            line.verticalAlignmentMode = .center
            line.horizontalAlignmentMode = .center

            // Tracking adds its space AFTER the last letter too, so a centred
            // tracked line sits half a space left of true. Nudging it back is the
            // difference between two stacked words that line up and two that very
            // nearly do. Small now, because the tracking is: the wide spacing went
            // with AvenirNext, and the system face at Black weight is already a
            // solid block of letterforms without being prised apart.
            line.position = CGPoint(x: type * 0.02,
                                    y: index == 0 ? leading / 2 : -leading / 2)
            wordmark.addChild(line)
        }

        wordmark.alpha = 0
        wordmark.run(.fadeIn(withDuration: 0.3))

        let float = SKAction.sequence([.moveBy(x: 0, y: 5, duration: 2.3),
                                       .moveBy(x: 0, y: -5, duration: 2.3)])
        float.timingMode = .easeInEaseOut
        wordmark.run(.repeatForever(float), withKey: "float")
    }

    private func buildButtons(centredOn playCentre: CGPoint,
                              playSize: CGSize,
                              iconSide: CGFloat,
                              iconRowY: CGFloat) {
        for old in [playButton, infoButton, settingsButton] { old?.removeFromParent() }

        let play = MenuButtonNode(primary: "PLAY",
                                  width: playSize.width, height: playSize.height,
                                  fill: RenderPalette.menuPlay)
        play.position = playCentre
        play.zPosition = 10
        addChild(play)
        playButton = play

        let info = MenuButtonNode(secondary: Glyphs.info, diameter: iconSide,
                                  fill: RenderPalette.menuInfo)
        let settings = MenuButtonNode(secondary: Glyphs.gear, diameter: iconSide,
                                      fill: RenderPalette.menuSettings)

        // Side by side under the pill, with enough air between them that a thumb
        // cannot mean both. They are the same size and sit on the same line because
        // they are the same KIND of thing - ranking them against each other would
        // be a third level of hierarchy on a screen that needs two.
        let gap = iconSide * 0.55
        info.position = CGPoint(x: playCentre.x - (iconSide + gap) / 2, y: iconRowY)
        settings.position = CGPoint(x: playCentre.x + (iconSide + gap) / 2, y: iconRowY)

        for button in [info, settings] {
            button.zPosition = 10
            button.alpha = 0
            button.run(.sequence([.wait(forDuration: 0.12),
                                  .fadeAlpha(to: 1, duration: 0.3)]))
            addChild(button)
        }

        infoButton = info
        settingsButton = settings

        // Offset from the wordmark's float, so the two never nod together. Two
        // things pulsing in step read as one mechanism, which is the note this
        // screen must not hit: the button would look like part of the title.
        play.breathe(after: 0.5)
    }

    /// What the game remembers about you. Nothing at all, the first time.
    private func buildRecord(centredOn centre: CGPoint) {
        childNode(withName: "record")?.removeFromParent()
        guard Prefs.matchesFinished > 0 else { return }

        let matches = Prefs.matchesFinished
        let played = "\(matches) MATCH\(matches == 1 ? "" : "ES")"

        let label = SKLabelNode()
        label.name = "record"
        label.attributedText = MenuButtonNode.text("BEST \(Prefs.bestScore)   ·   \(played)",
                                                   size: 12, weight: .semibold,
                                                   kern: 1.4,
                                                   colour: SKColor(white: 0, alpha: 0.38))
        label.verticalAlignmentMode = .center
        label.position = centre
        label.zPosition = 10
        addChild(label)
    }

    // Type for this whole screen lives in MenuButtonNode.text - one helper, one
    // typeface, one place. It was duplicated here and in the sheet, which is how
    // three files end up set in two and a half different fonts.

    // MARK: - Pressing it

    #if os(iOS) || os(tvOS)
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard let touch = touches.first, let view else { return }
        let point = touch.location(in: self)

        // The sheet gets first refusal on everything while it is up, which is what
        // makes it a sheet rather than a picture of one: nothing behind it can be
        // pressed through it.
        if sheet.isOpen {
            if sheet.closes(localPoint: touch.location(in: sheet)) {
                SoundPlayer.shared.play(.exit)
                sheet.dismiss()
            }
            return
        }

        guard !starting else { return }

        if let play = playButton,
           play.contains(localPoint: CGPoint(x: point.x - play.position.x,
                                             y: point.y - play.position.y)) {
            starting = true

            // On the press rather than when the match appears. The button's
            // animation and the fade to the map take the better part of half a
            // second between them, and a sound that arrives at the end of that
            // belongs to the scene change; one that arrives on the press belongs
            // to the finger.
            SoundPlayer.shared.play(.play)

            // And the rest of the screen stands down, so the button is the only
            // thing moving at the moment it is pressed.
            wordmark.removeAction(forKey: "float")

            play.press { [weak view] in
                view?.presentScene(GameScene.newGameScene(),
                                   transition: .fade(withDuration: 0.35))
            }
            return
        }

        if let info = infoButton,
           info.contains(localPoint: CGPoint(x: point.x - info.position.x,
                                             y: point.y - info.position.y)) {
            SoundPlayer.shared.play(.select)
            info.press { [weak self] in
                guard let self else { return }
                self.sheet.open(title: "HOW TO PLAY",
                                message: "Coming soon.",
                                on: self.size)
            }
            return
        }

        if let settings = settingsButton,
           settings.contains(localPoint: CGPoint(x: point.x - settings.position.x,
                                                 y: point.y - settings.position.y)) {
            SoundPlayer.shared.play(.select)
            settings.press { [weak self] in
                guard let self else { return }
                self.sheet.open(title: "SETTINGS",
                                message: "Coming soon.",
                                on: self.size)
            }
        }
    }
    #endif
}
